version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - QA/CI

  # Python requirements
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    assignees:
      - BoboTiG
    labels:
      - dependencies
