version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - htmlzip
  - epub
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
