build: off

image:
  - Visual Studio 2019

platform:
  - x64
  - x86

environment:
  fast_finish: true
  matrix:
    - PYTHON_VERSION: 3.10
    - PYTHON_VERSION: 3.9
    - PYTHON_VERSION: 3.8
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.5

matrix:
  allow_failures:
    - PYTHON_VERSION: 3.10
    - PYTHON_VERSION: 3.9

init:
  # Update Environment Variables based on matrix/platform
  - set PY_VER=%PYTHON_VERSION:.=%
  - set PYTHON=C:\PYTHON%PY_VER%
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)

  # Put desired Python version first in PATH
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - python -m pip install --upgrade pip tox

test_script:
  - tox -e py%PY_VER%
