build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  fast_finish: true
  matrix:
    - python: py35
      tox_env: py35
      python_path: c:\python35
    - python: py35-x64
      tox_env: py35
      python_path: c:\python35-x64
    - python: py36
      tox_env: py36
      python_path: c:\python36
    - python: py36-x64
      tox_env: py36
      python_path: c:\python36-x64
    - python: py37
      tox_env: py37
      python_path: c:\python37
    - python: py37-x64
      tox_env: py37
      python_path: c:\python37-x64
    - python: py38
      tox_env: py38
      python_path: c:\python38
    - python: py38-x64
      tox_env: py38
      python_path: c:\python38-x64

install:
  - python -m pip install virtualenv
  - python -m virtualenv env
  - env\Scripts\activate.bat
  - python -m pip install --upgrade pip tox

test_script:
  tox -e %tox_env%
