from .base import MSSBase


class MSS(MSSBase):
    def __del__(self) -> None: ...
    def __init__(self, display: str=None) -> None: ...
    def _set_argtypes(self) -> None: ...
    def _set_restypes(self) -> None: ...


def arch() -> int: ...
